/* 	
	This is the second problem on https://projecteuler.net.problem=2
	The program is supposed to find the solution to this problem:
	"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
	Even Fibonacci Numbers
*/

var fibNum = function() {
	var num1 = 1;
	var num2 = 1;
	var even1 = 0;
	var even2 = 0;
	var answer = 0;

	for (num1 = 1; num1 < 4000000 && num2 < 4000000; num1 = num1 + num2)
	{
		num2 = num1 + num2;

		if (num1 % 2 == 0)
		{
			even1 += num1;

			if (num2 % 2 == 0)
			{
				even2 += num2
			}
		}
		else if (num1 % 2 !== 0 && num2 % 2 == 0)
		{
			even2 += num2;
		}
	}

	answer = even1 + even2;

	document.getElementById('fibNum_result').innerHTML = answer;
}